### ISSUE TITLE
Crashes in ESM SSR: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by negezor** [vue-final/vue-final-modal#247]
### Version

vue-final-modal: 3.4.4
vue: 3.2.39

### OS

Windows (WSL)

### Reproduction Link
https://codesandbox.io/s/distracted-field-p1orne?file=/index.js

### Steps to reproduce

Import module

### What is Expected?

Imported module

### What is actually happening?

`Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`

**Comment by hunterliu1003** [comment]
fixed in [v3.4.8](https://www.npmjs.com/package/vue-final-modal/v/3.4.8)

**Comment by negezor** [comment]
Still not work, after removal https://github.com/vue-final/vue-final-modal/commit/1eccd3be6e0bd9f04dc22bc5b1ab31724c4f7982
```
import { VueFinalModal } from "vue-final-modal";
         ^^^^^^^^^^^^^
SyntaxError: Named export 'VueFinalModal' not found. The requested module 'vue-final-modal' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-final-modal';
const { VueFinalModal } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

```

**Comment by KitB** [comment]
Still broken for me too, same error as above. Using vite-ssg.
